# Generated by Django 5.0.4 on 2024-05-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='session_timeout',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
